### PR TITLE
Escape image in case of url String

### PR DESCRIPTION
**Pull request by RubenTeixeira**

### CODE REVIEW

**Review by thomraider12 — APPROVED** [review]

**Comment by diogotcorreia** [comment]
@freearhey Hey, could this be reviewed when you have the time? Thank you for your work!
Just pinging in case you missed this PR.

Some more context for the PR:
This tool is apparently not correctly escaping URLs for images, so if an image contains an `&`, an XML parser will expect it to be an XML entity instead and fail when it encounters the `=`.

Example:
```xml
<programme start="20241106223500 +0000" stop="20241107011500 +0000" channel="Lorem Ipsum"><title lang="en">Lorem Ipsum</title><image>https://example.com/example?foo=foo&bar=bar</image></programme>
```

```
System.Xml.XmlException: '=' is an unexpected token. The expected token is ';'. Line 164, position 299
```

**Comment by diogotcorreia** [comment]
@RubenTeixeira Taking a further look at your patch, I think you should change change this line to call `escapeString` like the rest of the code:

https://github.com/freearhey/epg-grabber/blob/5494988b3674508c51ffcdae76de4034ac79ef7d/src/xmltv.js#L178

e.g.

```js
[escapeString(image.value)]
```

And since you're at it, do the same for `createURLElement`.

It's probably a good idea to update the tests as well: https://github.com/freearhey/epg-grabber/blob/5494988b3674508c51ffcdae76de4034ac79ef7d/tests/xmltv.test.js

Let me know if you want me to open another PR instead, in case you're busy.

**Comment by freearhey** [comment]
Fixed in `v0.37.2`.

**Comment by diogotcorreia** [comment]
@freearhey any chance of updating this in https://github.com/iptv-org/epg? Thanks in advance

**Pull request closed without merging**
